In [1]:
import pandas as pd

In [2]:
stats = pd.read_csv('Full_NFL_Stats_2022.csv')

In [3]:
stats.head()

,Unnamed: 0,teamName,displayName,description,abbreviation,value,perGameValue,rank
0,0,Falcons,Fumbles,The number of times a player/team has fumbled ...,FUM,21.0,1.0,13.0
1,1,Falcons,Fumbles Lost,The number of times a fumble is recovered by t...,LST,12.0,NaN,4.0
2,2,Falcons,Forced Fumbles,The total number of forced fumbles.,FF,8.0,NaN,62.0
3,3,Falcons,Fumbles Recovered,The number of fumbles recovered.,FR,7.0,NaN,23.0
4,4,Falcons,Fumbles Touchdowns,The number of times a fumbles is recovered and...,FTD,1.0,NaN,8.0

In [4]:
ypg = stats.loc[stats['displayName'] == 'Rushing Yards Per Game']
ypg = ypg.sort_values(by='rank')

In [7]:
ypg.tail()

,Unnamed: 0,teamName,displayName,description,abbreviation,value,perGameValue,rank
3627,13,Rams,Rushing Yards Per Game,The average number of rushing yards per game.,YDS/G,97.706,NaN,27.0
887,13,Bengals,Rushing Yards Per Game,The average number of rushing yards per game.,YDS/G,95.500,NaN,29.0
6367,13,Chargers,Rushing Yards Per Game,The average number of rushing yards per game.,YDS/G,89.647,NaN,30.0
8559,13,Texans,Rushing Yards Per Game,The average number of rushing yards per game.,YDS/G,86.824,NaN,31.0
7189,13,Buccaneers,Rushing Yards Per Game,The average number of rushing yards per game.,YDS/G,76.941,NaN,32.0

In [24]:
fumbles = stats.loc[stats['displayName'] == 'Rushing Fumbles Lost']
fumbles = fumbles.sort_values(by='rank',ascending=False)

In [27]:
fumbles.tail()

,Unnamed: 0,teamName,displayName,description,abbreviation,value,perGameValue,rank
4720,10,Saints,Rushing Fumbles Lost,The number of times there is a run and then th...,LST,4.0,NaN,3.0
2802,10,Colts,Rushing Fumbles Lost,The number of times there is a run and then th...,LST,4.0,NaN,3.0
8008,10,Jaguars,Rushing Fumbles Lost,The number of times there is a run and then th...,LST,4.0,NaN,3.0
336,10,Bills,Rushing Fumbles Lost,The number of times there is a run and then th...,LST,5.0,NaN,1.0
8556,10,Texans,Rushing Fumbles Lost,The number of times there is a run and then th...,LST,5.0,NaN,1.0

In [17]:
downs = stats.loc[stats['displayName'] == 'Rushing 1st downs']
downs = downs.sort_values(by='rank')
downs = downs.drop_duplicates(subset=['teamName'])

In [19]:
downs.tail()

,Unnamed: 0,teamName,displayName,description,abbreviation,value,perGameValue,rank
2995,4,Colts,Rushing 1st downs,The number of times a rush results in a first ...,FDR,91.0,5.0,28.0
8554,8,Texans,Rushing 1st downs,The number of times a first down is picked up ...,FD,90.0,5.0,29.0
3817,4,Rams,Rushing 1st downs,The number of times a rush results in a first ...,FDR,89.0,5.0,30.0
5461,4,Jets,Rushing 1st downs,The number of times a rush results in a first ...,FDR,79.0,4.0,31.0
7184,8,Buccaneers,Rushing 1st downs,The number of times a first down is picked up ...,FD,79.0,4.0,31.0

In [22]:
td = stats.loc[stats['displayName'] == 'Rushing Touchdowns']
td = td.sort_values(by='rank')
td = td.drop_duplicates(subset=['teamName'])

In [23]:
td

,Unnamed: 0,teamName,displayName,description,abbreviation,value,perGameValue,rank
5722,7,Eagles,Rushing Touchdowns,The total number of rushing touchdowns.,RUSH,32.0,1.0,1.0
1433,11,Cowboys,Rushing Touchdowns,The total number of rushing touchdowns.,TD,24.0,1.0,2.0
2160,7,Lions,Rushing Touchdowns,The total number of rushing touchdowns.,RUSH,23.0,1.0,3.0
5174,7,Giants,Rushing Touchdowns,The total number of rushing touchdowns.,RUSH,21.0,1.0,4.0
6818,7,49ers,Rushing Touchdowns,The total number of rushing touchdowns.,RUSH,20.0,1.0,5.0
1159,11,Browns,Rushing Touchdowns,The total number of rushing touchdowns.,TD,19.0,1.0,6.0
4173,11,Vikings,Rushing Touchdowns,The total number of rushing touchdowns.,TD,18.0,1.0,7.0
790,7,Bears,Rushing Touchdowns,The total number of rushing touchdowns.,RUSH,18.0,1.0,7.0
3256,7,Chiefs,Rushing Touchdowns,The total number of rushing touchdowns.,RUSH,18.0,1.0,7.0
63,11,Falcons,Rushing Touchdowns,The total number of rushing touchdowns.,TD,17.0,1.0,10.0
2708,7,Titans,Rushing Touchdowns,The total number of rushing touchdowns.,RUSH,16.0,NaN,11.0
8188,7,Jaguars,Rushing Touchdowns,The total number of rushing touchdowns.,RUSH,16.0,NaN,11.0
7914,7,Panthers,Rushing Touchdowns,The total number of rushing touchdowns.,RUSH,16.0,NaN,11.0
6270,7,Steelers,Rushing Touchdowns,The total number of rushing touchdowns.,RUSH,16.0,NaN,11.0
337,11,Bills,Rushing Touchdowns,The total number of rushing touchdowns.,TD,15.0,NaN,15.0
6544,7,Chargers,Rushing Touchdowns,The total number of rushing touchdowns.,RUSH,15.0,NaN,15.0
5996,7,Cardinals,Rushing Touchdowns,The total number of rushing touchdowns.,RUSH,15.0,NaN,15.0
3804,7,Rams,Rushing Touchdowns,The total number of rushing touchdowns.,RUSH,15.0,NaN,15.0
8462,7,Ravens,Rushing Touchdowns,The total number of rushing touchdowns.,RUSH,14.0,NaN,19.0
1064,7,Bengals,Rushing Touchdowns,The total number of rushing touchdowns.,RUSH,14.0,NaN,19.0
5269,11,Jets,Rushing Touchdowns,The total number of rushing touchdowns.,TD,13.0,NaN,21.0
4721,11,Saints,Rushing Touchdowns,The total number of rushing touchdowns.,TD,12.0,NaN,22.0
2434,7,Packers,Rushing Touchdowns,The total number of rushing touchdowns.,RUSH,12.0,NaN,22.0
7092,7,Seahawks,Rushing Touchdowns,The total number of rushing touchdowns.,RUSH,12.0,NaN,22.0
3351,11,Raiders,Rushing Touchdowns,The total number of rushing touchdowns.,TD,12.0,NaN,22.0
3899,11,Dolphins,Rushing Touchdowns,The total number of rushing touchdowns.,TD,12.0,NaN,22.0
4447,11,Patriots,Rushing Touchdowns,The total number of rushing touchdowns.,TD,12.0,NaN,22.0
1886,7,Broncos,Rushing Touchdowns,The total number of rushing touchdowns.,RUSH,11.0,NaN,28.0
7461,11,Commanders,Rushing Touchdowns,The total number of rushing touchdowns.,TD,9.0,NaN,29.0
2982,7,Colts,Rushing Touchdowns,The total number of rushing touchdowns.,RUSH,8.0,NaN,30.0
8557,11,Texans,Rushing Touchdowns,The total number of rushing touchdowns.,TD,7.0,NaN,31.0
7187,11,Buccaneers,Rushing Touchdowns,The total number of rushing touchdowns.,TD,5.0,NaN,32.0

In [28]:
bottom_rb = []

for df in [ypg, fumbles, downs,td]:

    bottom_names = list(df['teamName'].tail(16))

    bottom_rb += bottom_names

name_counts = {name: bottom_rb.count(name) for name in set(bottom_rb)}

final_names = [name for name in name_counts.keys() if name_counts[name] == 4]

print(final_names)

['Colts', 'Saints', 'Texans', 'Broncos']